### ISSUE TITLE
Missing property keywords

### ISSUE THREAD

**Issue by gergoerdi** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#16]
`get`, `set` and `field` are keywords related to properties: https://kotlinlang.org/docs/reference/properties.html

**Comment by russel** [comment]
The statement is true, but what is needed is a statement of a problem with the Kotlin mode along with an example exposing the problem that needs solving. The example can then be formed into a test, which can then lead to a proposal for change of the code.

**Comment by gregghz** [comment]
It turns out that it's farily non-trivial to support these keywords correctly too. At least for get and set, these are only properly keywords in certain contexts (I don't know much about the field keyword, that might be simpler).

In addition, get and set have kind of a special case of indentation rules in intellij at least.

**Comment by ice1000** [comment]
WHY IS THIS STILL OPEN...

**Comment by gregghz** [comment]
@ice1000 I haven't had time to work on this lately. I'd love to get this fixed but it may be a bit before I can deal with this specific issue. If a PR was created I would definitely have time to review it. Thanks for checking out this project. I'd love for emacs to have better emacs support eventually.

**Comment by ice1000** [comment]
[Thanks](https://github.com/ice1000/dev-kt) :+1:

**Comment by gregghz** [comment]
This should be fixed in the next version heading the melpa in an hour or two.
